[build]
builder = "nixpacks"
buildCommand = "echo \"$MYSQL_ATTR_SSL_CA\" > /app/ca.pem && pip install -r requirements.txt && python manage.py collectstatic --noinput"

[deploy]
startCommand = "gunicorn Tourist_Place_Recommendation.wsgi:application --timeout 120"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.12.3"
PYTHONUNBUFFERED = "1"
DJANGO_SETTINGS_MODULE = "Tourist_Place_Recommendation.settings"

[[statics]]
gzip = true