# Generated by Django 5.0.4 on 2024-05-01 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Ratings', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Rating_count', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Address', models.CharField(max_length=255)),
                ('Map_link', models.URLField(max_length=500)),
                ('Review_1', models.TextField(default='')),
                ('Review_2', models.TextField(default='')),
                ('Review_3', models.TextField(default='')),
                ('openingHours_0_day', models.CharField(default='', max_length=200)),
                ('openingHours_0_hours', models.CharField(default='', max_length=200)),
                ('openingHours_1_day', models.CharField(default='', max_length=200)),
                ('openingHours_1_hours', models.CharField(default='', max_length=200)),
                ('openingHours_2_day', models.CharField(default='', max_length=200)),
                ('openingHours_2_hours', models.CharField(default='', max_length=200)),
                ('openingHours_3_day', models.CharField(default='', max_length=200)),
                ('openingHours_3_hours', models.CharField(default='', max_length=200)),
                ('openingHours_4_day', models.CharField(default='', max_length=200)),
                ('openingHours_4_hours', models.CharField(default='', max_length=200)),
                ('openingHours_5_day', models.CharField(default='', max_length=200)),
                ('openingHours_5_hours', models.CharField(default='', max_length=200)),
                ('openingHours_6_day', models.CharField(default='', max_length=200)),
                ('openingHours_6_hours', models.CharField(default='', max_length=200)),
                ('sentiment', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'dataset',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('with_whom', models.CharField(max_length=100)),
                ('review_text', models.TextField()),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tourist_App.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='review_photos')),
                ('photo_data', models.BinaryField(blank=True, null=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Tourist_App.review')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('otp', models.CharField(max_length=6, null=True)),
                ('user_name', models.CharField(max_length=200, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('gender', models.IntegerField()),
                ('category_prefs', models.CharField(default='', max_length=255)),
                ('groups', models.ManyToManyField(related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.CharField(max_length=50)),
                ('comments', models.TextField()),
                ('sentiment', models.IntegerField(default=None)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tourist_App.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tourist_App.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite',
                'unique_together': {('user', 'place')},
            },
        ),
    ]
