# Generated by Django 5.0.4 on 2024-05-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourist_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_prefs',
            field=models.CharField(default='', max_length=255),
        ),
    ]
