# Generated by Django 5.0.6 on 2024-07-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourist_App', '0003_remove_reviewphoto_photo_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetLoaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_loaded', models.BooleanField(default=False)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
